# 更多部署方式详见：http://ldapdoc.eryajf.net/pages/f081dc/

services:
  go-ldap-admin:
    image: cnxc/go-ldap-admin:0.5.18_2025-04-02
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./config/config.yml:/app/config.yml
      - ./data/go-ldap-admin/data:/app/data
    depends_on:
      - openldap
      - postgres

  openldap:
    image: osixia/openldap:1.5.0
    restart: always
    environment:
      - LDAP_DOMAIN=eryajf.net
      - LDAP_BASE_DN=dc=eryajf,dc=net
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=gyaL^kouIKVCz74oML@J^YJW1d9PqxLH
      - LDAP_CONFIG_PASSWORD=gyaL^kouIKVCz74oML@J^YJW1d9PqxLH
      - LDAP_READONLY_USER=false
      - KEEP_EXISTING_CONFIG=true
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_BACKEND=mdb
    tty: true
    stdin_open: true
    ports:
      - '389:389'
      - '636:636'
    volumes:
      - ./data/openldap/data:/var/lib/ldap
      - ./data/openldap/config:/etc/ldap/slapd.d

  # 可以不部署，仅用于查看数据 ldap 里的数据
  phpldapadmin:
    restart: always
    image: osixia/phpldapadmin:latest
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=openldap

  # 如果使用外部数据库，可以不用部署
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: dnZTP0Qg6bfKANVl
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --encoding=utf-8
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data
      TZ: "Asia/Shanghai"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
